export const slides = [
  {
    key: 'somethun',
    title: 'Organize your ingredients',
    text: `Do you want to spend less? Do you want to reduce your impulse purchases? Grocery lists 
      can help you. You'll buy only foods that you need.`,
    icon: 'md-settings',
    colors: ['#b0e8b3', '#61d167'],
    iconType: 'Ionicons',
    iconColors: '#61d167',
  },
  {
    key: 'somethun1',
    title: 'Mobile-oriented design',
    text: `You can manage all data from your phone. You always carry your smartphone, 
      instead of paper lists. Your lists on your phone, period.`,
    icon: 'mobile-phone',
    colors: ['#ccccff', '#6666ff'],
    iconType: 'FontAwesome',
    iconColors: '#6666ff',
  },
  {
    key: 'somethun2',
    title: 'Grocery lists customization',
    text: 'This is your own lists. You can do anything.',
    icon: 'ios-list',
    colors: ['rgba(227, 61, 73,0.5)', '#e33d49'],
    iconType: 'Ionicons',
    iconColors: '#e33d49',
  },
  {
    key: 'somethun3',
    title: 'Grocery lists customization',
    text: 'This is your own lists. You can do anything.',
    textArray: [
      { key: '1', text: 'Instant Handles' },
      { key: '2', text: 'Save and share your lists' },
      { key: '3', text: 'Plan your family budget' },
      { key: '4', text: 'Improve your health and live longer' },
      { key: '5', text: 'Save and share your lists' },
    ],
    icon: 'check-circle',
    colors: ['#ccebff', '#4db8ff'],
  },
];
